### ISSUE TITLE
Does not compile with gcc 7.1.1

### ISSUE THREAD

**Issue by antoyo** [RAttab/optics#20]
Here are the errors:
```
[4/52] Linking C executable bin/example
FAILED: bin/example 
: && /usr/bin/cc -g -std=gnu11 -pthread -D_GNU_SOURCE -DOPTICS_VERSION="1.1.1"  -rdynamic CMakeFiles/example.dir/test/example.c.o  -o bin/example  lib/liboptics_static.a lib/liboptics_static.a -lbsd -lrt && :
CMakeFiles/example.dir/test/example.c.o: In function `main':
/home/antoni/Telechargements/Source/optics/build/../test/example.c:70: undefined reference to `optics_timer_start'
/home/antoni/Telechargements/Source/optics/build/../test/example.c:74: undefined reference to `optics_timer_elapsed'
collect2: error: ld returned 1 exit status
[5/52] Building C object CMakeFiles/optics_poller_static.dir/src/utils/crest/crest.c.o
FAILED: CMakeFiles/optics_poller_static.dir/src/utils/crest/crest.c.o 
/usr/bin/cc  -I../src -I/usr/include/libmicrohttpd -I/usr/include/p11-kit-1 -g -std=gnu11 -pthread -D_GNU_SOURCE -DOPTICS_VERSION="1.1.1"   -pipe -g -O3 -Werror -march=native -Wall -Wextra -Wundef -Wcast-align -Wwrite-strings -Wunreachable-code -Wformat=2 -Wswitch-enum -Wswitch-default -Winit-self -Wno-strict-aliasing -Wno-missing-field-initializers -Wno-format-nonliteral -MD -MT CMakeFiles/optics_poller_static.dir/src/utils/crest/crest.c.o -MF CMakeFiles/optics_poller_static.dir/src/utils/crest/crest.c.o.d -o CMakeFiles/optics_poller_static.dir/src/utils/crest/crest.c.o   -c ../src/utils/crest/crest.c
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/crest.c: In function 'crest_call_cb.isra.6':
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/crest.c: In function 'microhttpd_cb':
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
In file included from ../src/utils/crest/crest.c:26:0:
../src/utils/crest/resp.c:85:5: error: argument 1 null where non-null expected [-Werror=nonnull]
     crest_resp_write(resp, reason, strnlen(reason, 1024));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/utils/crest/crest.c:12:0:
/usr/include/string.h:401:15: note: in a call to function 'strnlen' declared here
 extern size_t strnlen (const char *__string, size_t __maxlen)
               ^~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Comment by RAttab** [comment]
All fixed, reopen if you run into more issues.
